export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const UPDATE_SUBCATEGORIES = "UPDATE_SUBCATEGORIES"
export const UPDATE_MENSSUBCATEGORIES = "UPDATE_MENSSUBCATEGORIES"
export const UPDATE_WOMENSSUBCATEGORIES = "UPDATE_WOMENSSUBCATEGORIES"