export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_ALL_PRODUCTS = "UPDATE_ALL_PRODUCTS";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const UPDATE_SUBCATEGORIES = "UPDATE_SUBCATEGORIES"
export const UPDATE_MENSSUBCATEGORIES = "UPDATE_MENSSUBCATEGORIES"
export const UPDATE_WOMENSSUBCATEGORIES = "UPDATE_WOMENSSUBCATEGORIES"

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";
